---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

#  - type: dnf
#    repos:
#      copr:
#        - lizardbyte/stable

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/lizardbyte/stable/repo/fedora-%OS_VERSION%/lizardbyte-stable-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - Sunshine
      - tailscale
        
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
      - scope: user # Also add Flathub user repo, but no user packages
        install:
          - org.srb2.SRB2
          - io.github.srb2.rphys
          - org.kartkrew.RingRacers
          - io.github.dvlv.boxbuddyrs
          - com.usebottles.bottles
          - org.libretro.RetroArch
          - org.keepassxc.KeePassXC
          - io.mrarm.mcpelauncher
          - org.inkscape.Inkscape
          - org.kde.gwenview
          - io.github.celluloid_player.Celluloid
          - com.valvesoftware.Steam # unofficial, but sandboxed
          - org.localsend.localsend_app
          - org.libreoffice.LibreOffice
          - org.luanti.luanti
          - org.qbittorrent.qBittorrent

  - type: systemd
    system:
      enabled:
        - tailscaled.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
